---
- hosts: nodes
  connection: local
  name: Reboot servers
  gather_facts: False

  tasks:
  - name: Configure Server Power Setting
    dellemc_change_power_state:
       idrac_ip:   "{{ idrac_ip }}"
       idrac_user: "{{ idrac_user }}"
       idrac_pwd:  "{{ idrac_password }}"
       change_power: "GracefulRestart"
